;
; File generated by cc65 v 2.18 - Git N/A
;
	.autoimport on
	.importzp	sp
	.importzp	tmp1, ptr1
	.export		_ultimate_ci_write

; void __near__ ultimate_ci_write (__near__ const unsigned char *, unsigned int)

.segment	"CODE"

.proc	_ultimate_ci_write: near

.segment	"CODE"

	sta tmp1
	ldy #$00
	lda (sp),y
	sta ptr1
	iny
	lda (sp),y
	sta ptr1 + 1
write_page:
	txa
	beq write_rest
	dex
	ldy #$00
loop_page:
	lda (ptr1),y
	sta $DF1D
	iny
	bne loop_page
	inc ptr1 + 1
	jmp write_page
write_rest:
	lda tmp1
	beq end
	ldy #$00
loop_rest:
	lda (ptr1),y
	sta $DF1D
	iny
	cpy tmp1
	bne loop_rest
end:
	jmp incsp2

.endproc

